# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7858dfcd51cb6197ae42d4f659e187ffec3ea852baab5fea305b748144fc48ece4257e0db2eb19ca552c95f54223b433cdf896688711dbe2f5ec2a756e66b2da

test:
  secret_key_base: 15a54190e8d774b4dfef28511cd071deff5a4244eec896ac22d170dd6657338b0647d1b12d5df0e8254a574c4b78669c9c221d0ad45332f43c291ae53eee6d0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
